### PR TITLE
Add compose multiplatform support to voyager-koin (Closes #158)

### LINKED ISSUE #158: Add multiplatform support for voyager-koin
Seems like koin now supports compose multiplatform. Does that mean we can also add multiplatform support to voyager-koin? Already having any plans on doing so in the near future? See https://github.com/InsertKoinIO/koin/issues/1208#issuecomment-1536504478.

### PR DESCRIPTION
**Pull request by geworfener**
* Add new koin-compose dependency
* Setup Module for Compose Multiplatform
* Tested on Android, iOS, Desktop JVM, Web JS

### CODE REVIEW

**Comment by mslalith** [comment]
Koin supports Compose Multiplatform -> https://github.com/InsertKoinIO/koin/issues/1208#issuecomment-1536504478
@Syer10 Looks like this can be merged now

**Comment by alfietapping** [comment]
Looking to use this

**Comment by ferranpons** [comment]
The same! This would be very useful! @adrielcafe 🙏

**Comment by aplha98** [comment]
plz update the doc for that

**Pull request merged**
