### PR TITLE
Multiplatform Voyager

### PR DESCRIPTION
**Pull request by terrakok**
I've migrated voyager-core to Kotlin Multiplatform with Android+JVM targets.

### CODE REVIEW

**Comment by terrakok** [comment]
Done. It can be merged to master. The Core and the Navigator modules can be used in desktop compose apps

**Comment by terrakok** [comment]
Sample desktop app with Voyager navigation:
https://github.com/Kotlin/kmm-production-sample/blob/8985e952b72f4ff619ac9db9d2c4e0b2377ae8a7/composeApp/src/jvmMain/kotlin/com/github/jetbrains/rssreader/desktopApp/App.kt#L61

P.S.: before launch you have to publish Voyager version 2.0.0 to MavenLocal

**Comment by terrakok** [comment]
https://user-images.githubusercontent.com/3532155/146031292-e1f65041-0533-4cc5-ada0-5944df77e96c.mp4

**Review by programadorthi — APPROVED** [review]

**Review by adrielcafe — APPROVED** [review]

**Comment by adrielcafe** [comment]
Thanks for your contribution @terrakok !

**Pull request merged**
