### PR TITLE
fix: event emit on destroy state #280

### LINKED ISSUE #280: Crashing with `java.lang.IllegalStateException: no event up from DESTROYED`
~Ever since we upgraded from Voyager 1.0.0-rc05, we've been getting this crash.~
Edit: I misremembered. I believe we've always had this crash since we introduced the Voyager tabs

We're currently on version 1.0.0-rc08, but the most recent updates don't seem to have changed anything that would fix this issue.

The stack trace is:
```
Fatal Exception: java.lang.IllegalStateException: no event up from DESTROYED
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:250)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
       at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner.emitOnStopEvents(AndroidScreenLifecycleOwner.java:107)
       at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner.access$emitOnStopEvents(AndroidScreenLifecycleOwner.java:44)
       at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner$LifecycleDisposableEffect$1$invoke$$inlined$onDispose$1.dispose(AndroidScreenLifecycleOwner.java:490)
       at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:86)
       at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1126)
       at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
       at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:109)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
       at android.view.Choreographer.doFrame(Choreographer.java:1045)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

We have about ~20-30 crashes every 7 days, which is not a lot considering the size of our userbase, but we would like to fix the issue nonetheless.

Unfortunately, I haven't been able to reproduce the issue at all. I'm not entirely sure how it could happen, and I've tried quite a lot of things. I believe the issue can definitely be in our integration, of course.

We can't share the code, but our navigation is more or less like this:

```
BottomSheetNavigator {
  TabNavigator {
    CurrentTab()
  }
}
```

Each tab has a Navigator as well:
```
Navigator(screen) { navigator ->
        LaunchedEffect(navigator) {
            viewModel.reselected.collectLatest { navigator.popUntilRoot() }
        }
        NavigatorTransition(navigator)
    }
```

All ours tabs are classes and have unique keys. It also happened when the classes were objects and regular `Screen`s. We added `TabDisposable` to our `TabNavigator` as well. The crash happened with and without it too.

It seems to happen mostly when returning to the root of a tab from some other screens, such as:
Initial tab -> Product screen -> ... -> Back to initial tab -> Crash

Do you have any clues why or how this crash could happen? I've tried looking at the source code of `AndroidScreenLifecycleOwner`, and all I could think of would be lifecycle events being handled multiple times when not always necessary due to `DisposableEffect`'s `onDispose` being called.

~This didn't happen when we were using `1.0.0-rc05` though. It started happening once we updated to `1.0.0-rc07`, and is still happening on `1.0.0-rc08`.~ - this has happened since we introduced Voyager tabs in the project.

Might be worth noting that we do use other `Activity`s, and that the `Activity` with the tabs navigator is not the app's "first" `Activity`.

### PR DESCRIPTION
**Pull request by DevSrSouza**
This PR fixes #280

### CODE REVIEW

**Comment by DevSrSouza** [comment]
For testing the solution, you can apply this git patch, open the sample app and go to `Basic Navigation` flow.

```patch
diff --git a/samples/android/build.gradle.kts b/samples/android/build.gradle.kts
index 3dcaa77..9406b66 100644
--- a/samples/android/build.gradle.kts
+++ b/samples/android/build.gradle.kts
@@ -15,6 +15,7 @@ android {
     defaultConfig {
         applicationId = "cafe.adriel.voyager.sample"
     }
+    dataBinding.enable = true
 }
 
 kapt {
@@ -49,5 +50,17 @@ dependencies {
     implementation(libs.hilt.android)
     kapt(libs.hilt.compiler)
 
+    implementation("androidx.core:core-ktx:1.9.0")
+    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.1")
+    implementation("androidx.activity:activity-compose:1.7.2")
+    implementation(platform("androidx.compose:compose-bom:2023.10.01"))
+    implementation("androidx.compose.ui:ui")
+    implementation("androidx.compose.ui:ui-graphics")
+    implementation("androidx.compose.ui:ui-tooling-preview")
+    implementation("androidx.compose.material3:material3")
+    debugImplementation("androidx.compose.ui:ui-tooling")
+    debugImplementation("androidx.compose.ui:ui-test-manifest")
+    implementation("androidx.compose.ui:ui-viewbinding")
+
     debugImplementation(libs.leakCanary)
 }
diff --git a/samples/android/src/main/java/cafe/adriel/voyager/sample/basicNavigation/BasicNavigationActivity.kt b/samples/android/src/main/java/cafe/adriel/voyager/sample/basicNavigation/BasicNavigationActivity.kt
index babfc12..3135fae 100644
--- a/samples/android/src/main/java/cafe/adriel/voyager/sample/basicNavigation/BasicNavigationActivity.kt
+++ b/samples/android/src/main/java/cafe/adriel/voyager/sample/basicNavigation/BasicNavigationActivity.kt
@@ -4,7 +4,31 @@ import android.os.Bundle
 import android.util.Log
 import androidx.activity.ComponentActivity
 import androidx.activity.compose.setContent
+import androidx.compose.foundation.layout.Box
+import androidx.compose.foundation.layout.fillMaxSize
+import androidx.compose.material.Button
+import androidx.compose.material.CircularProgressIndicator
+import androidx.compose.material.Text
+import androidx.compose.runtime.Composable
+import androidx.compose.runtime.LaunchedEffect
+import androidx.compose.runtime.getValue
+import androidx.compose.runtime.mutableStateOf
+import androidx.compose.runtime.remember
+import androidx.compose.runtime.setValue
+import androidx.compose.ui.Alignment
+import androidx.compose.ui.Modifier
+import androidx.compose.ui.platform.LocalLifecycleOwner
+import androidx.compose.ui.viewinterop.AndroidViewBinding
+import cafe.adriel.voyager.core.screen.Screen
+import cafe.adriel.voyager.core.screen.ScreenKey
+import cafe.adriel.voyager.core.screen.uniqueScreenKey
+import cafe.adriel.voyager.navigator.LocalNavigator
 import cafe.adriel.voyager.navigator.Navigator
+import cafe.adriel.voyager.navigator.currentOrThrow
+import cafe.adriel.voyager.sample.databinding.LayoutDataBindingBinding
+import cafe.adriel.voyager.transitions.SlideTransition
+import kotlinx.coroutines.delay
+import kotlinx.coroutines.isActive
 
 class BasicNavigationActivity : ComponentActivity() {
 
@@ -12,13 +36,59 @@ class BasicNavigationActivity : ComponentActivity() {
         super.onCreate(savedInstanceState)
 
         setContent {
-            Navigator(
-                screen = BasicNavigationScreen(index = 0),
-                onBackPressed = { currentScreen ->
-                    Log.d("Navigator", "Pop screen #${(currentScreen as BasicNavigationScreen).index}")
-                    true
+            SlideNavigator(InitialScreen())
+        }
+    }
+}
+
+@Composable
+private fun SlideNavigator(navScreen: Screen) {
+    Navigator(navScreen) { navigator ->
+        SlideTransition(navigator)
+    }
+}
+
+
+class InitialScreen : Screen {
+    override val key: ScreenKey = uniqueScreenKey
+
+    @Composable
+    override fun Content() {
+        val navigator = LocalNavigator.currentOrThrow
+        Button(onClick = { navigator.push(Screen1()) }) {
+            Text(text = "Push new Screen")
+        }
+    }
+}
+
+class Screen1 : Screen {
+    override val key: ScreenKey = uniqueScreenKey
+
+    @Composable
+    override fun Content() {
+        Box(modifier = Modifier.fillMaxSize()) {
+            var show by remember { mutableStateOf(false) }
+            LaunchedEffect(key1 = Unit) {
+                while (isActive) {
+                    delay(250)
+                    show = !show
+                }
+            }
+            if (!show) {
+                CircularProgressIndicator(modifier = Modifier.align(Alignment.Center))
+            } else {
+                val lifecycleOwner = LocalLifecycleOwner.current
+                AndroidViewBinding(
+                    factory = { inflater, parent, attachToParent ->
+                        LayoutDataBindingBinding.inflate(inflater, parent, attachToParent)
+                            .apply {
+                                this.lifecycleOwner = lifecycleOwner
+                            }
+                    },
+                ) {
+                    this.text = "Show: $show"
                 }
-            )
+            }
         }
     }
 }
diff --git a/samples/android/src/main/res/layout/layout_data_binding.xml b/samples/android/src/main/res/layout/layout_data_binding.xml
new file mode 100644
index 0000000..344c4d6
--- /dev/null
+++ b/samples/android/src/main/res/layout/layout_data_binding.xml
@@ -0,0 +1,14 @@
+<?xml version="1.0" encoding="utf-8"?>
+<layout xmlns:android="http://schemas.android.com/apk/res/android">
+
+    <data>
+        <variable
+            name="text"
+            type="String" />
+    </data>
+    <TextView
+        android:layout_width="match_parent"
+        android:layout_height="wrap_content"
+        android:text="@{text}" />
+
+</layout>
```

**Comment by Kashif-E** [comment]
@DevSrSouza  can we get an alpha release for this?

**Comment by DevSrSouza** [comment]
@Kashif-E published in `1.1.0-alpha02`

**Comment by Kashif-E** [comment]
Thanks @DevSrSouza

**Pull request merged**
