### PR TITLE
Add `tag` argument to `Screen.getScreenModel`

### PR DESCRIPTION
**Pull request by arslan-charyyev-pc**
Hello. My use case involves creating multiple instances of the same `ScreenModel` via hilt's assissted injection, as demonstrated here: https://voyager.adriel.cafe/screenmodel/hilt-integration#assistedinject. The issue is that the current `Screen.getScreenModel` function does not allow us to specify a tag to differentiate screen models. This PR is designed to address that.

### CODE REVIEW

**Review by DevSrSouza — APPROVED** [review]

**Comment by DevSrSouza** [comment]
@arslan-charyyev-pc a rebase will be required because of the changes in CRLF -> LF

**Comment by arslan-charyyev-pc** [comment]
I've submitted the initial PR with a quick GitHub patch, and rebased via GitHub as well, so I'm not sure which line endings are used now. But GH says that this branch has no conflicts, so I assume that it was resolved.

**Comment by Syer10** [comment]
Lol it is not, you can tell by how the git changes look in github. Try this `git add --renormalize voyager-hilt/src/main/java/cafe/adriel/voyager/hilt/ScreenModel.kt`

**Comment by arslan-charyyev-pc** [comment]
Thanks, @Syer10. Is it fixed this time?

**Comment by Syer10** [comment]
It is 👍

**Pull request merged**
